# netlify.toml


# Esta sección define cómo se enrutarán las solicitudes
[[redirects]]
  # Desde la raíz de tu sitio, redirige a tu página principal
  from = "/*"
  to = "dist/index.html"
  status = 200